### ISSUE TITLE
jwt 

### ISSUE THREAD

**Issue by omerfurkankaplan** [yashjoshi-dotcom/College_Bazaar#9]
Hello, I added a user. I logged in with the user. When I add a product to sell, I get this error and it throws me to login, I can't login again.
![image](https://user-images.githubusercontent.com/60521051/199089934-6e4c0f54-743a-49fd-9861-92e087a49db6.png)

**Comment by yashjoshi-dotcom** [comment]
Hi @omerfurkankaplan 
Please make a config.env file in the backend directory. The format of the file will remain same as given in [example file](https://github.com/yashjoshi-dotcom/College_Bazaar/blob/main/backend/config.env.example)
Assign a long random string to the JWT_KEY environment variable. 
It should start working.
In case of any further assistance required, pls let me know and provide additional info such as what functions are working / what functions are impacted . 
This way I will be able to help you out in a much more swift manner.

**Comment by yashjoshi-dotcom** [comment]
@omerfurkankaplan  Have myself encountered the same error. It was due to some issues with the cookie parser. Have corrected it. Pls fetch the updates and let me know if you are still facing the issue.

**Comment by yashjoshi-dotcom** [comment]
Closing the issue the bug has been resolved.
Please open a new bug if you are facing any issues. 
Thanks for your time :)
